### ISSUE TITLE
zeth sync leads to ValueError

### ISSUE THREAD

**Issue by Ben-Haslam** [clearmatics/zeth#425]
I've been going through the old zeth tutorial here@ https://github.com/clearmatics/web-pub-project-testnet-bakerloo/blob/ce091aa9e1ccf3c47a1d9193d0a1a2041e708d00/docs/protocol-suite/zeth.md

Other than a few name changes it holds up, until I try to run a command with `zeth`:

`zeth sync`

```bash
SYNCHING blocks (2304402 - 2305687)
Traceback (most recent call last):
  File "/home/benhaslam/clearmatics/zeth/client/env/bin/zeth", line 11, in <module>
    load_entry_point('zeth', 'console_scripts', 'zeth')()
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/benhaslam/clearmatics/zeth/client/zeth/cli/zeth_sync.py", line 28, in sync
    chain_block_number = do_sync(
  File "/home/benhaslam/clearmatics/zeth/client/zeth/cli/utils.py", line 349, in do_sync
    return _do_sync()
  File "/home/benhaslam/clearmatics/zeth/client/zeth/cli/utils.py", line 309, in _do_sync
    for mix_result in get_mix_results(
  File "/home/benhaslam/clearmatics/zeth/client/zeth/core/mixer_client.py", line 653, in get_mix_results
    for event_data in logs:
  File "/home/benhaslam/clearmatics/zeth/client/zeth/core/contracts.py", line 219, in get_event_logs
    logs = web3.eth.getLogs(filter_params)
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'failed to get logs for block'}
```

If I try to deposit funds to zeth: `zeth mix --out zeth-address.pub,2 --vin 2 --wait`

```bash
send_contract_call: size=1369
0x47d2512679b1ada0e9609d1d48c1cd90ca6457485853ca8194ea7a51f6b32322
SYNCHING blocks (2304402 - 2304631)
Traceback (most recent call last):
  File "/home/benhaslam/clearmatics/zeth/client/env/bin/zeth", line 11, in <module>
    load_entry_point('zeth', 'console_scripts', 'zeth')()
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/benhaslam/clearmatics/zeth/client/zeth/cli/zeth_mix.py", line 135, in mix
    do_sync(zeth_client.web3, wallet, pp, tx_hash, zeth_note_short_print)
  File "/home/benhaslam/clearmatics/zeth/client/zeth/cli/utils.py", line 339, in do_sync
    _do_sync()
  File "/home/benhaslam/clearmatics/zeth/client/zeth/cli/utils.py", line 309, in _do_sync
    for mix_result in get_mix_results(
  File "/home/benhaslam/clearmatics/zeth/client/zeth/core/mixer_client.py", line 653, in get_mix_results
    for event_data in logs:
  File "/home/benhaslam/clearmatics/zeth/client/zeth/core/contracts.py", line 219, in get_event_logs
    logs = web3.eth.getLogs(filter_params)
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/benhaslam/clearmatics/zeth/client/env/lib/python3.8/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'failed to get logs for block'}
```

**Comment by dtebbs** [comment]
Closing as this has been confirmed as an issue with the node implementation being used.
